import api from "./client";

export const operationsApi = {
  summary: () => api.get("/operations/dashboard/summary"),
  wards: () => api.get("/operations/wards"),
  createWard: (payload) => api.post("/operations/wards", payload),
  beds: (wardId) => api.get("/operations/beds", { params: wardId ? { ward_id: wardId } : {} }),
  createBed: (payload) => api.post("/operations/beds", payload),
  updateBed: (id, payload) => api.put(`/operations/beds/${id}`, payload),
  allocateBed: (id, payload) => api.post(`/operations/beds/${id}/allocate`, null, { params: payload }),
  dischargeBed: (id, payload) => api.post(`/operations/beds/${id}/discharge`, null, { params: payload }),
  reserveBed: (id, payload) => api.post(`/operations/beds/${id}/reserve`, null, { params: payload }),
  transferBed: (id, payload) => api.post(`/operations/beds/${id}/transfer`, null, { params: payload }),
  bedAnalytics: () => api.get("/operations/analytics/beds"),
  wardAnalytics: () => api.get("/operations/analytics/wards"),
  resources: () => api.get("/operations/resources"),
  createResource: (payload) => api.post("/operations/resources", payload),
  staff: () => api.get("/operations/staff"),
  createStaff: (payload) => api.post("/operations/staff", payload),
  schedules: () => api.get("/operations/schedules"),
  createSchedule: (payload) => api.post("/operations/schedules", payload),
  alerts: () => api.get("/operations/alerts"),
  createAlert: (payload) => api.post("/operations/alerts", payload),
  notifications: () => api.get("/operations/notifications"),
  createNotification: (payload) => api.post("/operations/notifications", payload),
  forecast: (resourceName) => api.get("/operations/forecast/resource-demand", { params: { resource_name: resourceName } }),
  forecastComparison: (resourceName) => api.get("/operations/forecast/model-comparison", { params: { resource_name: resourceName } }),
  optimize: (payload) => api.post("/operations/optimization/recommendations", payload),
  optimizationRecommendations: () => api.get("/operations/optimization/recommendations"),
  scheduleRecommendations: (payload) => api.post("/operations/scheduling/recommendations", payload),
  detectAlerts: (payload) => api.post("/operations/alerts/detect", payload),
};
